### PR TITLE
GUI overhaul

### PR DESCRIPTION
**Pull request by ChrisMisan**
PR content:
- added results display
- added comparator names and text alignment
- added default values
- fixed delinking issues

image
image

### CODE REVIEW

**Comment by przemq20** [comment]
Przy próbie dodania node'a dostaję błąd:
image

**Comment by ChrisMisan** [comment]
Please make sure you're on the correct branch and provide minimal reproducible example.

**Comment by ChrisMisan** [comment]
@Mexolius please validate the dispatch procedure. It seems all queries are being sent to the size consumer. Maybe it was fixed by https://github.com/Mexolius/TKImages/pull/14/ ?

**Comment by Mexolius** [comment]
@ChrisMisan Could you explain how to reproduce the bug? I sent the message with both consumers working and it only went to color consumer. Maybe you have the old scala confing somehow? Try recreating the queues

**Comment by ChrisMisan** [comment]
@Mexolius if it works for you then it's ok. I guess it was fixed by the latest hotfix.

**Review by przemq20 — APPROVED** [review]

**Pull request merged**
